### ISSUE TITLE
General Issue: make use of testthat 3e

### ISSUE THREAD

**Issue by esimms999-gsk** [pharmaverse/admiralvaccine#112]
### Background Information

We want to make use of testthat 3rd edition, also known as testthat 3e. This is stricter testing than previous versions of testthat and may require changes to some of the tests to keep the results from being "noisy". See [this article](https://testthat.r-lib.org/articles/third-edition.html) and [this blog post](https://www.tidyverse.org/blog/2022/02/upkeep-testthat-3/) for upgrading to testthat 3e.

Note: The admiral package was upgraded to testthat 3e for the 1Q2023 release. And the admiraltemplate package makes use of testthat 3e. This can be seen in the DESCRIPTION file with the testthat version >= 3.0.0 and Config/testthat/edition: 3.

### Definition of Done

We want testthat 3e to be used and any warnings or "noisy" messages in tests to be addressed.

**Comment by esimms999-gsk** [comment]
I do not seem to have access to this repo for assigning this issue or adding it to a project.

**Comment by bms63** [comment]
I can add to admiralvaccines board.  You can only assign issues/add to project board if you are a member of admiralvaccines team.  Want to join up!?!

**Comment by esimms999-gsk** [comment]
Yes, please.
