### ISSUE TITLE
Onboarding:  issue for test purposes

### ISSUE THREAD

**Issue by iaugu** [pharmaverse/admiralvaccine#13]
### Onboarding tasks for Core (Roche-GSK) Team Members

- [ ] Given a tour of Github from a Core member
- [ ] Understand how to Create Issues and do a Pull Request
- [ ] Understand the Programming Strategy
- [ ] Read and understand [Developer Guides Articles](https://pharmaverse.github.io/admiral/index.html)
- [ ] Invited to all relevant meetings - Stand Ups, Retrospective, Sprint Planning, Question/Comments, Backlog, Community Meeting
- [ ] Given access to Box and relevant documents
- [ ] Given write access to Github Repository
- [ ] Slack channel invites to admiral and admiral_dev
- [ ] Introduction to Teams ways of working

### Onboarding tasks for non-Core Team Members

- [ ] Given a tour of Github from a Core member
- [X] Understand how to Create Issues and do a Pull Request
- [X] Understand the Programming Strategy
- [ ] Read and understand [Developer Guides Articles](https://pharmaverse.github.io/admiral/index.html)
- [ ] Invited to all relevant meetings - Question/Comments, Community Meeting
- [ ] Given write access to Github Repository
- [ ] Slack channel invites to admiral
- [X] Introduction to Teams ways of working

**Comment by bms63** [comment]
Ohh... @pharmaverse/admiralvaccines I think we should update this template for our vaccine developers.  

https://github.com/pharmaverse/admiralvaccine/blob/main/.github/ISSUE_TEMPLATE/05_onboard.yml

I will make an issue!
