### ISSUE TITLE
General Issue: Test issue

### ISSUE THREAD

**Issue by federicobaratin** [pharmaverse/admiralvaccine#18]
### Background Information

This is a test issue in order to understand the logic behind this mechanism.

### Definition of Done

Please, resolve the issue.

**Comment by federicobaratin** [comment]
Closed

**Comment by bms63** [comment]
Nicely done Federico!!

**Comment by federicobaratin** [comment]
Hi Ben!

Thanks a lot for the help.

I am not able to assign issues to Andrea Pammolli (and he is not able to push into GitHub/admiralvaccines the branch created in R).
The error he had is related to the permissions.

Thanks!

**Comment by federicobaratin** [comment]
Test finished.
