### ISSUE TITLE
Documentation: Update website navbar with two buttons for slack and github issues

### ISSUE THREAD

**Issue by manciniedoardo** [pharmaverse/admiralvaccine#225]
### Let us know where something needs a refresh or put your idea here!

See [corresponding update](https://github.com/pharmaverse/admiral/pull/2182%5D) on admiral website.

**Comment by manciniedoardo** [comment]
@pharmaverse/admiralvaccines is anyone interested in this small PR?

**Comment by ahasoplakus** [comment]
Hi @arjoon-r could you look into this?
