### ISSUE TITLE
Enhancement: Remove existing test data and reference them from pharmaversesdtm

### ISSUE THREAD

**Issue by sahas56** [pharmaverse/admiralvaccine#228]
### Please select a category the issue is focused on?

Function Documentation

### Let us know where something needs a refresh or put your idea here!

Follow the discussion here https://github.com/pharmaverse/pharmaversesdtm/pull/74#pullrequestreview-1687019736

**Comment by ahasoplakus** [comment]
All references to `admiral.test` to get replaced with `pharmaversesdtm`
