### ISSUE TITLE
General Issue: STEP 1 ADIS - Merge IS with SUPPIS

### ISSUE THREAD

**Issue by federicobaratin** [pharmaverse/admiralvaccine#26]
### Background Information

Step 1 - ADIS workflow: to merge IS with SUPPIS.

### Definition of Done

To obtain final merged immunogenicity dataset.

**Comment by federicobaratin** [comment]
I finished the utilities for IS and SUPPIS combination. It should be applicable for all the supplemental domains. Please @ap765541  and @YaminiBollu check it out :)
@bms63 please let me know if everything is in line with way of working.

**Comment by federicobaratin** [comment]
Updated code.
Use of function combie_supp from metatools package.

**Comment by bms63** [comment]
Hi @federicobaratin can you create a Pull Request so I can review please?
