### ISSUE TITLE
Feature Request:  Request for Data folder in Vaccine Admiral Repo

### ISSUE THREAD

**Issue by jsrivj** [pharmaverse/admiralvaccine#4]
### Feature Idea

Vaccine Mock Data Folder: This folder is for Storing the mock (dummy) SDTM data required for Vaccine ADaM Development, we have generated 6 SDTM (DM,EX,AE,VS,CE,FA) also be including IS required for ADCE, ADFA, ADIS to start with. The data is pulled from Vaccine CDISC TUG or SDTM IG or Scenario based on comments received for Pfizer, GSK, J&J Colleagues. It has 7 programs and individual programs for each domain and one util for generating basic SDTM meta data from the List of variables given in SDTM IG. It will be helpful place the above-mentioned files in a folder to share across pharma and make updates as applicable (As discussed in the admiral vaccine meeting). (Please be informed that this mock data is for vaccine development since the Admiral Test data was not sufficient)

### Relevant Input

input to the meta data is a excel sheet containing Variable Name, Variable Label, and Variable time (Charecter / Numeric) . Few data records are taken from Vaccine CDISC TUG (might expand based on client specific requirements)

### Relevant Output

SDTM data frames in Rda file

### Reproducible Example/Pseudo Code

Kindly provide the folder and access, so the code can be uploaded for review and enhancement

**Comment by bms63** [comment]
Hi @jsrivj please do a Pull Request for uploading this data.  Spec is also really nice to have!
