### ISSUE TITLE
Documentation:  Update example for derive_param_maxsev

### ISSUE THREAD

**Issue by bms63** [pharmaverse/admiralvaccine#41]
### Please select a category the issue is focused on?

Function Documentation

### Let us know where something needs a refresh or put your idea here!

@arjoon-r You should create some dummy data using tibble package and use it with your example.  We want a user to be able to quickly run your example in real-time to understand how the function works.

![image](https://user-images.githubusercontent.com/10111024/218320277-dbf4ea4c-66e1-4bb2-9f9d-5c146076da2f.png)

**Comment by arjoon-r** [comment]
Hi Ben,

Actually that was an outdated code. Which i had  uploaded for a demo
purpose.

Please take a look at this latest version of maximum severity function. I
have already uploaded in a new branch.

Branch link:
https://github.com/pharmaverse/admiralvaccine/tree/16_adface_maxsev_utility

Good day! :)

Regards,
Arjun

**Comment by bms63** [comment]
Can you run `devtools:document()` often as you develop your code.  Take a look at #9 for how I fixed some of the documenation issues in that branch.  I am merging it all into `devel/main` but your new branch will overwrite it once you are done.

Also, I would go ahead and make a PR for your new branch so the actions so start giving you feedback
